// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscsmuweklduijqjoibh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY3NtdXdla2xkdWlqcWpvaWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODgzNzQsImV4cCI6MjA2NTU2NDM3NH0.SK9-R_t1m_6cj1z9OLhRZf7Wi98bqho-srJS1UJ3aZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);